version: '2'
template:
  name: "Get feedback - emoting (SSME)"
  description: "Deploy your own OpenWhisk Emoting app."
  required:
    - build
    - repo
    - deploy

toolchain:
  name: 'get-feedback-emoting-smme-{{timestamp}}'

services:
  repo:
    service_id: githubpublic
    parameters:
      repo_name: 'get-feedback-emoting-smme'
      repo_url: 'https://github.com/egzontina/get-feedback-emoting-smme'
      type: fork
      has_issues: false
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{services.repo.parameters.repo_name}}'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          REPO: repo
          CF_APP_NAME: 'get-feedback-emoting-smme'
          ORG_NAME: '{{form.pipeline.parameters.app-organization}}'
          REGION_ID: '{{form.pipeline.parameters.app-region}}'
          SPACE_NAME: '{{form.pipeline.parameters.app-space}}'
        execute: true

form:
  pipeline:
    parameters:
      app-region: 'ibm:yp:us-south'
    schema:
      $ref: deploy.json
